// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL from environment
    // SQLite for local: file:./dev.db
    // PostgreSQL for production: postgresql://...
    url: process.env.DATABASE_URL || "file:./dev.db",
  },
});
